name: Build Linux 7.0 Debs (Banana Pi - ARMHF)

on:
  workflow_dispatch: 

jobs:
  build-kernel-armhf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev \
        libdw-dev pkg-config gcc-arm-linux-gnueabihf rsync kmod debhelper dwarves

    - name: Download and Extract Kernel
      run: |
        wget https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-7.0.tar.xz
        tar -xvf linux-7.0.tar.xz

    - name: Configure Kernel
      run: |
        cd linux-7.0
        
        # Pega o seu config sunxi da raiz do repositório
        cp ../config-7.0.0-rc6-edge-sunxi .config
        
        # Ajusta para 32-bit e preenche os NEW do 7.0
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- olddefconfig
        
        # Mata o debug para o pacote ficar leve
        scripts/config --disable DEBUG_INFO
        scripts/config --disable DEBUG_INFO_BTF

    - name: Build Debian Packages
      run: |
        cd linux-7.0
        
        export DEB_BUILD_OPTIONS=nocheck
        
        # O sublinhado corrigido: DPKG_FLAGS
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j$(nproc) bindeb-pkg \
          KDEB_PKGVERSION=$(date +%Y%m%d-%H%M) \
          KDEB_NOSRCPACKAGE=1 \
          DPKG_FLAGS="-d"

    - name: Upload Debs
      uses: actions/upload-artifact@v4
      with:
        name: linux-7.0-armhf-debs
        path: "*.deb"