name: Build LibreELEC 9.2 (S805 - MXQ) - Com Cache Direto

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-libreelec:
    name: Compilando LibreELEC S805
    runs-on: ubuntu-latest

    steps:
      - name: Liberando espaço no Runner
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo apt-get clean

      - name: Clonando LibreELEC-AML (dtechsrv)
        uses: actions/checkout@v4
        with:
          repository: dtechsrv/LibreELEC-AML
          path: LibreELEC-AML

      - name: O COFRE - Salvando Downloads e Progresso
        uses: actions/cache@v4
        with:
          # Salva a pasta de downloads E a pasta onde a compilação acontece
          path: |
            LibreELEC-AML/sources
            LibreELEC-AML/build.LibreELEC-AML.S805.arm-9.2
          # A chave usa o ID da rodada. O restore puxa sempre a mais recente.
          key: libreelec-s805-cache-${{ github.run_id }}
          restore-keys: |
            libreelec-s805-cache-

      - name: Corrigindo Hash do Wireguard (Remendo de 2020)
        run: |
          sed -i 's/ec08772216da73a2f6a925927ce794fe9686ba169bb774e451d34199db19795c/00aa32dffb87f6273977fe068c17091693d9475a0a96cfa35dbb02ddbe663e7b/g' LibreELEC-AML/packages/network/wireguard-tools/package.mk
          sed -i 's/83dd096f793641a513f8c1f0ea9999b442873e3c7c590b313d155cbe99d0eab9/94abf7aa9827e399e47b2b4ee7ec46537aae9c9e4064c440253fdcbadc6a9884/g' LibreELEC-AML/packages/network/wireguard-linux-compat/package.mk

      - name: A MÁGICA - Compilação Direta no Ubuntu 18.04
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ubuntu:18.04 /bin/bash -c "
            # 1. Preparação (Dependências)
            apt-get update && \
            apt-get install -y gcc make git unzip wget xz-utils g++ bc gperf zip lzop patchutils m4 default-jre python python3 xfonts-utils xsltproc libxml-parser-perl sudo libncurses5-dev libjson-perl gawk nodejs && \
            
            # 2. Usuário Builder
            useradd -m -s /bin/bash builder && \
            chown -R builder:builder /workspace && \
            
            # 3. COMPILAÇÃO REAL (E download sob demanda)
            echo 'Tudo pronto! Indo direto para a compilação...' && \
            sudo -u builder bash -c 'cd /workspace/LibreELEC-AML && PROJECT=S805 DEVICE=HD18Q ARCH=arm make image' && \
            
            # 4. Permissões finais
            chmod -R 777 /workspace
          "

      - name: Resgatando o Arquivo Final
        uses: actions/upload-artifact@v4
        with:
          name: LibreELEC-S805-Imagem
          path: LibreELEC-AML/target/*.img.gz