name: Build LibreELEC 9.2 (S805 - MXQ)

on:
  workflow_dispatch:

jobs:
  build-libreelec:
    name: Compilando LibreELEC S805
    runs-on: ubuntu-latest

    steps:
      - name: Liberando espaço no Runner (Essencial)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo apt-get clean

      - name: Clonando LibreELEC-AML (dtechsrv)
        uses: actions/checkout@v4
        with:
          repository: dtechsrv/LibreELEC-AML
          path: LibreELEC-AML

      - name: A MÁGICA - Compilando isolado no Ubuntu 18.04 (Sem Root)
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ubuntu:18.04 /bin/bash -c "
            apt-get update && \
            apt-get install -y gcc make git unzip wget xz-utils g++ bc gperf zip lzop patchutils m4 default-jre python python3 xfonts-utils xsltproc libxml-parser-perl sudo && \
            useradd -m -s /bin/bash builder && \
            chown -R builder:builder /workspace && \
            sudo -u builder bash -c 'cd /workspace/LibreELEC-AML && PROJECT=S805 DEVICE=HD18Q ARCH=arm make image' && \
            chmod -R 777 /workspace/LibreELEC-AML/target
          "

      - name: Resgatando o Arquivo
        uses: actions/upload-artifact@v4
        with:
          name: LibreELEC-S805-Imagem
          path: LibreELEC-AML/target/*.img.gz